---
# tasks file for docker-securitization
- name: "Generate CA, Server and Client Certificate"
  include_role:
    name: alexinthesky.secure-docker-daemon

- name: "Edit docker service configuration"
  become: yes
  blockinfile:
    path: /etc/systemd/system/docker.service.d/override.conf
    block: |
      [Service]
      ExecStart=
      ExecStart=/usr/bin/dockerd -H fd:// -H tcp://0.0.0.0:2376 --tlsverify --tlscacert={{ docker_cert_basepath }}/ca.pem --tlscert={{ docker_cert_basepath }}/server-cert.pem --tlskey={{ docker_cert_basepath }}/server-key.pem

- name: "Restart Docker"
  become: yes
  ansible.builtin.systemd:
    daemon_reload: yes
    name: docker
    state: restarted