---
# Task for docker Swarm configuration

- name: "Check if Swarm Mode is enabled"
  command: docker info
  changed_when: false
  register: docker_info

- name: Init docker swarm on manager node
  command: docker swarm init --advertise-addr "{{ ansible_ssh_host }}:2377"
  when: "docker_info.stdout.find('Swarm: active') == -1
    and 'docker_swarm_manager' in group_names"

- name: Get docker swarm worker token 
  command: docker swarm join-token -q worker
  register: worker_token
  delegate_to: "{{ groups['docker_swarm_manager'][0] }}"
  delegate_facts: true
  when: "'docker_swarm_worker' in group_names"

- name: Join worker node
  command: docker swarm join --token "{{ worker_token.stdout }}" --advertise-addr {{ ansible_ssh_host }} "{{ hostvars[groups['docker_swarm_manager'][0]]['ansible_ssh_host'] }}:2377"
  when: "docker_info.stdout.find('Swarm: active') == -1
    and docker_info.stdout.find('Swarm: pending') == -1
    and 'docker_swarm_worker' in group_names"