---

- name: Main Playbook
  hosts: all
  become: yes
  vars_files: 
    - "./variables.yaml"
  roles:
    - vm_configuration
    - geerlingguy.docker  ## Docker Installation
    - docker_secure
    - docker_swarm
    - docker_test